export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_CAMIONES_PENDING = 'REQUEST_CAMIONES_PENDING';

export const REQUEST_CAMIONES_SUCCESS = 'REQUEST_CAMIONES_SUCCESS';

export const REQUEST_CAMIONES_FAILED = 'REQUEST_CAMIONES_FAILED';
